services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      BACKEND_URL: http://backend:5000/api # Link to backend

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"